SCR_ObjectBrushArrayConfig {
 m_aObjectArray {
  SCR_ObjectBrushObjectBase "{65E7503B3A6A5340}" {
   m_Prefab "{735E970ACBB1B473}Prefabs/Rocks/Granite/Granite_Boulder_01.et"
   m_fRandomPitchAngle 180
   m_fRandomRollAngle 180
   m_fRandomYawAngle 180
   m_bOverrideRandomization 1
  }
  SCR_ObjectBrushObjectBase "{65E7503B3B92FF86}" {
   m_Prefab "{1F0AA3EA77753B5D}Prefabs/Rocks/Granite/Granite_Boulder_02.et"
   m_fRandomPitchAngle 180
   m_fRandomRollAngle 180
   m_fRandomYawAngle 180
   m_bOverrideRandomization 1
  }
  SCR_ObjectBrushObjectBase "{65E7503B3BBD0470}" {
   m_Prefab "{038844285FEE0D7A}Prefabs/Rocks/Granite/GraniteStone_01.et"
   m_fRandomPitchAngle 180
   m_fRandomRollAngle 180
   m_fRandomYawAngle 180
   m_bOverrideRandomization 1
  }
  SCR_ObjectBrushObjectBase "{65E7503B3B0F3F7E}" {
   m_Prefab "{8A403C31EFCF153F}Prefabs/Rocks/Granite/GraniteStone_03.et"
   m_fRandomPitchAngle 180
   m_fRandomRollAngle 180
   m_fRandomYawAngle 180
   m_bOverrideRandomization 1
  }
 }
}