SCR_ObjectBrushArrayConfig : "{D471E9B4021A80A3}Configs/Workbench/ObjectBrush/OB_GraniteSurfaceStone_Forest.conf" {
 m_aObjectArray {
  SCR_ObjectBrushObjectBase "59D8692A5819801C" {
   m_fRandomYawAngle 180
   m_bOverrideRandomization 1
  }
  SCR_ObjectBrushObjectBase "{65E92BBBD88ED420}" {
   m_Prefab "{3B3F46AE50FE582D}PrefabLibrary/Rocks/Granite/GraniteSurfaceStone_02/GraniteSurfaceStone_02.et"
   m_fBotDistance 8
   m_fVerticalOffset -10
   m_fRandomYawAngle 180
   m_bOverrideRandomization 1
   m_bAlignToNormal 1
  }
  SCR_ObjectBrushObjectBase "{65E92BBBD14AC0D1}" {
   m_Prefab "{576B724EEC3AD703}PrefabLibrary/Rocks/Granite/GraniteSurfaceStone_01/GraniteSurfaceStone_01.et"
   m_fBotDistance 8
   m_fVerticalOffset -10
   m_fRandomYawAngle 180
   m_bOverrideRandomization 1
   m_bAlignToNormal 1
  }
 }
}