SCR_ObjectBrushArrayConfig : "{D471E9B4021A80A3}Configs/Workbench/ObjectBrush/OB_GraniteSurfaceStone_Forest.conf" {
 m_aObjectArray {
  SCR_ObjectBrushObjectBase "{664767B5F5E1CCD9}" : "59D8692A5819801C" {
   m_Prefab "{102F94404E45E8D6}PrefabLibrary/Rocks/Granite/Granite_Cluster_Large_01.et"
   m_fRandomYawAngle 180
   m_bOverrideRandomization 1
  }
  SCR_ObjectBrushObjectBase "{664767B5F5E1B273}" {
   m_Prefab "{6761B2CC21C9C7CD}PrefabLibrary/Rocks/Granite/Granite_Cluster_06.et"
   m_fBotDistance 8
   m_fVerticalOffset -10
   m_fRandomYawAngle 180
   m_bOverrideRandomization 1
   m_bAlignToNormal 1
  }
  SCR_ObjectBrushObjectBase "{664767B5F5E1B264}" {
   m_Prefab "{0B35862C9D0D48E3}PrefabLibrary/Rocks/Granite/Granite_Cluster_05.et"
   m_fBotDistance 8
   m_fVerticalOffset -10
   m_fRandomYawAngle 180
   m_bOverrideRandomization 1
   m_bAlignToNormal 1
  }
 }
}