SCR_ObjectBrushArrayConfig {
 m_aObjectArray {
  SCR_ObjectBrushObjectBase "{65ECB01C2F7E2CA1}" {
   m_Prefab "{C43DBD0E6B897116}Prefabs/Rocks/Granite/GraniteSurfaceCliff_01_smooth.et"
   m_fRandomYawAngle 180
   m_bOverrideRandomization 1
   m_bAlignToNormal 1
  }
  SCR_ObjectBrushObjectBase "{65ECB01C2F7E2CA8}" {
   m_Prefab "{EE199AAD9D671739}Prefabs/Rocks/Granite/GraniteSurfaceCliff_02_smooth.et"
   m_fRandomYawAngle 180
   m_bOverrideRandomization 1
   m_bAlignToNormal 1
  }
  SCR_ObjectBrushObjectBase "{65ECB01C2F7E2CAE}" {
   m_Prefab "{3655D895A864D8AD}Prefabs/Rocks/Granite/GraniteSurfaceCliff_03_smooth.et"
   m_fRandomYawAngle 180
   m_bAlignToNormal 1
  }
 }
}