SCR_MissionHeader {
 World "{91B45792CE3AA3DD}worlds/Alpenfestung/GM_Alpenfestung.ent"
 SystemsConfig "{8DDC2A311929D52F}Configs/Systems/GameMasterSystems.conf"
 m_sName "Game Master - Alpine Fortress"
 m_sAuthor "Kexanone"
 m_sDescription "#AR-Editor_Mission_GM_Eden_Description"
 m_sIcon "{1CF079D01934F0B3}UI/Textures/AF_Preview.edds"
 m_sLoadingScreen "{1CF079D01934F0B3}UI/Textures/AF_Preview.edds"
 m_sPreviewImage "{1CF079D01934F0B3}UI/Textures/AF_Preview.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
}